### ISSUE TITLE
Create Unit Tests

### ISSUE THREAD

**Issue by kitsonk** [dojo/grunt-dojo2#1]
We need to create unit tests for the following:
- [ ] tasks/rename
- [ ] tasks/rewriteSourceMaps
- [ ] tasks/updateTsconfig
- [ ] tasks/uploadCoverage

**Comment by rishson** [comment]
@kitsonk @pdfernhout this keeps getting bumped. I'm assuming this is still incomplete, but we are struggling to get time devoted to it?

**Comment by agubler** [comment]
@rishson yup, tests are still needed.
