### ISSUE TITLE
Generated dojo theme key should not include `.m`

### ISSUE THREAD

**Issue by tomdye** [dojo/grunt-dojo2#132]
**Bug** 

Need to edit 
https://github.com/dojo/grunt-dojo2/blob/master/tasks/util/postcss.ts#L27
To remove the `.m` from our theme key as our css files are now named `.m.css`.

I believe it is safe to simply change this replace to `path.basename(outputPath, '.m.css')` as we only css-module process files with this file extension.

**Comment by kitsonk** [comment]
Is there anything to address in `dojo build` along these lines?
