### ISSUE TITLE
Ability to update package.json metadata on publish

### ISSUE THREAD

**Issue by rishson** [dojo/grunt-dojo2#135]
It would save lots of time if we could update npm config data when doing a publish,

e.g. ability to update `maintainers, url, bugs` etc when publishing a version.

We could use this ability to do things such as change the `url` from `dojotoolkit.org` to `dojo.io` on all 25 Dojo 2 repos.

**Comment by rishson** [comment]
Thinking how to pass the changes to the release task:

`release config set url=someUrl`

works for simple single changes, but if you wanted anything more advanced, say, removing a name from the `maintainers` list, then you would need a different mechanism.

**Comment by kitsonk** [comment]
@matt-gadd we should consider whatever value there is in this issue under the changes to the release automation, or otherwise close the issue.
