### ISSUE TITLE
Allow config to be overridden for ts compile grunt tasks

### ISSUE THREAD

**Issue by agubler** [dojo/grunt-dojo2#18]
Currently the `grunt-ts` targets defined (`dev`, `dist` and `esm`) used to compile typescript are preset and consumers are unable to override certain config attributes such as `declaration`.

Allow consumers to override the presets for certain attributes.

**Comment by kitsonk** [comment]
Is your feeling that what we do in things like [dojo/widgets](https://github.com/dojo/widgets/blob/8ef474816c350b026c54200253ed7f9e990e6e9a/Gruntfile.js) doesn't meet this requirement?

**Comment by agubler** [comment]
@kitsonk yeah that won't change the arguments used to generate the temporary `tsconfig.json` files for the compile tasks, as it uses the projects `tsconfig.json` as the base and then overrides specific attributes for each of the targets (these are currently not configurable).

So we certainly could use the same mechanism but we do need to update the `ts.ts` options to respect them.

**Comment by kitsonk** [comment]
Ah, ok, externalise some sort of config that gets "mixed in" to the generation of the `tsconfig.json` per target?

**Comment by agubler** [comment]
precisely
