### ISSUE TITLE
Add pre-release check for checking against the remote

### ISSUE THREAD

**Issue by matt-gadd** [dojo/grunt-dojo2#33]
Currently the pre-release task checks for a dirty branch, as well as the branch being on master. It would be nice if we could check that the local branch aligns with the dojo remote also.

**Comment by kitsonk** [comment]
The following will determine if the local and remote have diverged.

```sh
$ git status -uno
```

Don't know how to fold that into the script though.

**Comment by agubler** [comment]
Superseded by dojo/scripts
