### ISSUE TITLE
Log in to npm when using the release task

### ISSUE THREAD

**Issue by matt-gadd** [dojo/grunt-dojo2#34]
The task currently checks whether the user is logged in, and that the user has permissions to publish the package. It might be worth adding the capability to pass credentials to the task and it logging in automatically (as well as logging out after the release is completed).

**Comment by agubler** [comment]
The release task here is being superseded by `dojo/scripts. Future enhancements to the release process should be added to that repository.

**Comment by agubler** [comment]
Issue moved to [dojo/scripts #2](https://github.com/dojo/scripts/issues/2) via [**ZenHub**](https://www.zenhub.com/)
