### ISSUE TITLE
Add support to publish an uber package

### ISSUE THREAD

**Issue by matt-gadd** [dojo/grunt-dojo2#36]
An `uber` package is essentially the same as the structure of the git repo, with the added `dist` folder with the generated outputs for `umd` and `esm`.

We'd like to publish the `uber` packages under the `@dojo` scope. For example:
`dojo-has` (umd) ---> `@dojo/has` (uber).

The work to add this to the release task is trivial, but one thing we must deal with is switching the dojo dependencies in the `package.json` (which are the umd ones) to use the uber equivalents, so that in effect, when you pull an `uber` package down from npm you will get any of the dependencies of it in `uber` form also.

**Comment by kitsonk** [comment]
@matt-gadd I am not sure this reflects our current thinking and is unactionable in its current state.  I maybe wrong, and if I am, we should clarify the scope of this issue.

**Comment by agubler** [comment]
Superseded by dojo/scripts
