### ISSUE TITLE
Add support to publish an ESM package

### ISSUE THREAD

**Issue by matt-gadd** [dojo/grunt-dojo2#37]
This would actually be easier than https://github.com/dojo/grunt-dojo2/issues/36, as we'd just ship `esm` in the same flat structure as our `umd` ones. This means no folder structure changes. 

We'd have to pick another name for the packages in npm (possibly `dojo-has-es`, or `dojo-has-esm`), but the main question is - given the state of `esm` module consumption at the moment i'm not sure how valuable publishing the `esm` target is.

**Comment by kitsonk** [comment]
#36 still has advantages of bundling the TypeScript source, which when bundling and subsequent consumption in a tool chain might be the best for a downstream developer.

Also, in our public UMD packages, we haven't yet addressed things like minification, etc.  The uber package should consider things like providing a minified rolled-up package as well, or we need to agree that we will add `index.min.js` and `main.min.js` to our UMD packages.

I think we should wait to publish and ESM package until we have an implemented module loader in either NodeJS or one of the main browsers that is feature complete (even if it is still not under a flag).

**Comment by kitsonk** [comment]
I suspect we would want to close #36 and think about some solution aligned to this.  But having both issues open seems redundant.

**Comment by kitsonk** [comment]
Changing this into an Epic to deal with an sub-issues needed to make this happen.

**Comment by matt-gadd** [comment]
A lot of what was originally put in this issue is superfluous/outdated due to it being well over a year old and pre us moving over to namespaced packages `@dojo`. I think in the short term we can now just ship esm as `.mjs` alongside our existing umd `.js` files, although we' have to check whether TypeScript will actually resolve `.mjs` files, if not that puts in a difficult situation for our packaging.

**Comment by agubler** [comment]
I believe that has been completed, if not please feel free to re-open.
