### ISSUE TITLE
Clean /typings

### ISSUE THREAD

**Issue by kitsonk** [dojo/grunt-dojo2#4]
(but only those installed by typings)

**Comment by agubler** [comment]
@kit, is it safe to assume that everything in `typings` was installed by `typings`? Or are there times that isn't true?

**Comment by kitsonk** [comment]
@agubler it used to be that way, but that is clearly "unsafe" and we shouldn't do that.  So anything that was "custom" was moved to `dojo/typings` and should be referenced via the `typings.json` so that there is never a need to persist `/typings` in the package.
