### ISSUE TITLE
Source Maps are not working without the Typescript source

### ISSUE THREAD

**Issue by agubler** [dojo/grunt-dojo2#42]
with the flat packaging, the typescript source is no longer being distributed - need to add `inlineSources` to include the source in the map file.

**Comment by kitsonk** [comment]
I can see what we did here, and that is right in that it only applies for dist builds, but just wanted to note as a reminder that Intern does not currently handle inline sources, and still needs that flag turned off.

**Comment by agubler** [comment]
Thanks @kitsonk, I didn't know that so fortunate that it's only for the `dist` build.
