### ISSUE TITLE
Source Maps, Debugging and Names

### ISSUE THREAD

**Issue by kitsonk** [dojo/grunt-dojo2#46]
It is great that in our distributions our source maps inline the source, but the one challenge is that the name of the original file makes it a bit confusing when debugging.

For example, here is a partial stack trace:

```
TypeError: Cannot read property 'get' of undefined
  at factory.on  <src/mixins/createEvented.ts:167:44>
  at initialize  <_build/src/mixins/createRenderMixin.js:291:35>
  at <src/compose.ts:179:42>
  at Array.forEach  <native>
  at Object.factory  <src/compose.ts:179:25>
```

Where `createEvented` is in `node_modules/dojo-compose/mixins/createEvented.js` and `compose` is in `node_modules/dojo-compose/compose.js`.  When you have multiple packages brought together, all the stack traces make it look like all the original code is all part of one big package in `src` when actually it can be various packages.  I think this will also make future debugging difficult because it will be "oh, what package is that from?" if the names of the module aren't obvious, let alone people using 3rd party packages.

It would be good to inject the package name into the name in the source map on a distribution build, so it at least did something like `dojo-compose/src/mixins/createEvented.ts`.

**Comment by matt-gadd** [comment]
@kitsonk yeah that sucks. Do we think this might be a bug/enhancement for tsc? when the `--inlineSources` flag is set, the `sources` array should only ever contain the source filename (no directory structure). You don't need to inject the actual folder structure/package name, as for inline sourcemaps it will map to the directory the source file was in (if that makes sense)

**Comment by matt-gadd** [comment]
@kitsonk for now I can easily fix this in the dist task.

**Comment by kitsonk** [comment]
@matt-gadd agreed that we should at least attempt to ask TypeScript.  Did you want to open the issue?  But also agree that we might want to find an alternative solution for now.

**Comment by matt-gadd** [comment]
@kitsonk I will raise an issue no worries. PR raised that will fix during dist in the mean time.
