### ISSUE TITLE
Release Task: Add flag to skip the recommended package.json changes

### ISSUE THREAD

**Issue by agubler** [dojo/grunt-dojo2#50]
Dojo Loader does not require all the changes (specifically setting `main` to `main.js` and `typings` to `undefined`) to the `package.json` that the release task performs automatically.

Perhaps can optionally add a flag to the task that indicates these updates require skipping or potentially add an attribute to the `package.json` itself that indicates that the changes are not required.

Third option would be to just remove these updates from the release entirely.

**Comment by matt-gadd** [comment]
These were only meant to be temporary anyway, until we had a stable set of package shapes and should probably be just removed.
