### ISSUE TITLE
Ability to express dev links for CI

### ISSUE THREAD

**Issue by kitsonk** [dojo/grunt-dojo2#51]
One of the challenges we have is using CI when on an upstream dev branch.  It would be great if we had some sort of solution to indicate alternative branches of code to substitute in, build and then link into the main package.  It would also be great if this was somehow was configurable externally to the code in the repo so it would accidentally leak into `master` when merging.

I know it is a bit of a pipe dream, but when dreaming, dream big, right?

**Comment by agubler** [comment]
I suppose an issue with this is that if a Pull Request was built on CI successfully by substituting the normal dependency to one build from a branch (containing code it depends on); someone could mistake this as the PR is ready to be merged and we end up with downstream changes in master before the changes they depend on.

**Comment by kitsonk** [comment]
Yes, maybe all these problems go away when we can publish breaking change versions of packages without those leaking into the valid semver ranges of other published packages.

**Comment by kitsonk** [comment]
This issue has largely become redundant.  Closing.
