### ISSUE TITLE
Integrate CSS Modules/postcss build task

### ISSUE THREAD

**Issue by kitsonk** [dojo/grunt-dojo2#54]
We should integrate the CSS Modules/postcss build task into `grunt-dojo2`.

**Comment by bitpshr** [comment]
@kitsonk, is this still needed in addition to the cli command? If so, let me know and I'll knock this out.

**Comment by bitpshr** [comment]
After discussion with @kitsonk, this is being put on hold indefinitely in favor of [dojo/cli-css-modules](http://github.com/dojo/dojo/cli-css-modules) and the PostCSS Grunt tasks in [dojo/widgets](http://github.com/dojo/widgets). If a need arises to have CSS module support in repos beyond dojo/widgets and the CLI isn't sufficient, we can revisit this.
