### ISSUE TITLE
Release Task: Ignore tests directory on publish

### ISSUE THREAD

**Issue by agubler** [dojo/grunt-dojo2#55]
Enhancing the release task to ignore the tests directory on publish will allow us to normalise our package build to a single directory with a single uniform set of compile options (configured in each `tsconfig.json`).

**Comment by matt-gadd** [comment]
I can look at this, but is it as simple as ignoring the tests?

`grunt dist` generates a directory of `dist/umd` which contains what would've been the `src` directory.

`grunt dev` generates a directory of `_build` which contains a `src` directory and a `test` directory.

**Comment by kitsonk** [comment]
Let's fit this into whatever we need to do to automate the release task.

**Comment by agubler** [comment]
Superseded by dojo/scripts
