### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by devpaul** [dojo/grunt-dojo2#57]
We should have documentation covering the standard tasks (i.e. `dev`, `test`, `watch`, `dist`, and `release`). I'd like to know what they each handle and about their standard task flow. For instance, what standard structure does `grunt-dojo2` expect, what release options are available to me, can I do a dry-run of a release (because release and dist look like separate flows), and how can I add to `devTasks` or `distTasks`?

**Comment by dylans** [comment]
This was closed via #62.
