### ISSUE TITLE
Integrate Reporter.ts

### ISSUE THREAD

**Issue by kitsonk** [dojo/grunt-dojo2#61]
@iyegoroff commented on [Sat Aug 13 2016](https://github.com/dojo/core/issues/184)

Hi, I see that in tests you use similar console [reporters](https://github.com/dojo/core/blob/master/tests/support/Reporter.ts) across your projects. Is it accessible as a separate npm-module or something like that?

---

@kitsonk commented on [Sun Aug 14 2016](https://github.com/dojo/core/issues/184#issuecomment-239669072)

Actually, we should move it to `grunt-dojo2`, which contains all our tool chain items, right now it is just in the `dojo2-package-template`.

---

@iyegoroff commented on [Sun Aug 14 2016](https://github.com/dojo/core/issues/184#issuecomment-239672110)

Ok, thanks for reply.

---

@dylans commented on [Thu Oct 20 2016](https://github.com/dojo/core/issues/184#issuecomment-255006425)

We never actually moved this reporter.

**Comment by agubler** [comment]
@kitsonk we can perhaps put all the test config in grunt-dojo2...
