### ISSUE TITLE
Copy d.ts files from src/ on `dist` task

### ISSUE THREAD

**Issue by mwistrand** [dojo/grunt-dojo2#63]
Unfortunately, the current TS compiler does not include copy any existing `d.ts` files when generating `d.ts` files for `.ts` modules. As such, `$ grunt dist` likewise does not include any existing `d.ts` files, which has caused problems elsewhere (e.g., dojo/core#209). It would be helpful if existing `src/**/*.d.ts` were copied into the `dist/umd` directory when running `$ grunt dist` so that consuming packages won't run into compiler errors about dependencies referencing modules that do not exist.

**Comment by kitsonk** [comment]
There is already a `copy:staticDefinitionFiles` that is part of the configuration.  It just needs to be added to the `dist` task.

**Comment by mwistrand** [comment]
Awesome. Thanks @matt-gadd!
