### ISSUE TITLE
grunt link should only include production dependencies

### ISSUE THREAD

**Issue by matt-gadd** [dojo/grunt-dojo2#67]
At the moment we are symlinking to the packages node_modules, which includes dev dependencies. This can have a habit of causing some type resolution problems due to the dev dependencies.

From now on we should just install the production dependencies in `dist/umd` rather than symlinking

**Comment by kitsonk** [comment]
@matt-gadd considering our preferred method now is installing a tar, is there any action we want/need to take here?

**Comment by agubler** [comment]
grunt link is no longer used
