### ISSUE TITLE
Replace lodash with dojo-core

### ISSUE THREAD

**Issue by kitsonk** [dojo/grunt-dojo2#71]
The usage of lodash in `grunt-dojo2` can be easily replaced with `dojo-core`.

The usage of [deepClone](https://github.com/dojo/grunt-dojo2/blob/91d990fda75cb0786c10fa116bd064462925380b/tasks/ts.ts#L49) can be replaced with `dojo-core/lang#duplicate` and [merge](https://github.com/dojo/grunt-dojo2/blob/91d990fda75cb0786c10fa116bd064462925380b/tasks/ts.ts#L53) can be replaced with `dojo-core/lang#assign` or `dojo-core/lang#deepAssign`.

**Comment by dylans** [comment]
I started working on this at https://github.com/dylans/grunt-dojo2/commit/eaca2eea29313ee217061c9c17aefa88209a65da , but there's a fair amount of cruft (e.g. the package is using a rather old version of dojo-loader). This package probably needs a more thorough updating of dependencies when addressing this issue.
