### ISSUE TITLE
Change main/fork from bryanforbes to dojo

### ISSUE THREAD

**Issue by dylans** [dojo/grunt-dojo2#78]
Currently this repo is a fork of bryanforbes' original work, though we've moved so far past the original that we should switch this around so that dojo/grunt-dojo2 is the primary repo.

**Comment by agubler** [comment]
@dylans Is the best way of doing that to delete the repo on github, recreate it and then push all the history, branches and tags back up to the new repo?

**Comment by dylans** [comment]
@agubler I'm not sure... that sounds reasonable to me, but I'm not sure if anything else is relying on Bryan's version (e.g. Intern 3.x's reliance on the old dojo/dojo2, etc.)?

**Comment by dylans** [comment]
This was fixed for beta1.
