### ISSUE TITLE
Don't process widgets.css as a CSS module

### ISSUE THREAD

**Issue by bitpshr** [dojo/grunt-dojo2#94]
Per discussion with @tomdye, the widgets repo will include a `main.css` file that imports all component CSS files. This file should be excluded from PostCSS module compilation.

**Comment by tomdye** [comment]
Can we rename to `widgets.css` please. `main.css` aligns too closely to `main.ts` and thats misleading.

**Comment by tomdye** [comment]
@bitpshr Can you confirm that the widgets.css file will work with your dialog if loaded via AMD please and close this issue?
